package br.edu.ufam.scfpcu.model;
// Generated Jan 9, 2014 11:42:56 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name = "cargo", catalog = "scfpcu")
public class Cargo implements java.io.Serializable {

	private Integer idCargo;
	private String cargo;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Usuario> usuarios_1 = new HashSet<Usuario>(0);

	public Cargo() {
	}

	public Cargo(String cargo) {
		this.cargo = cargo;
	}
	public Cargo(String cargo, Set<Usuario> usuarios, Set<Usuario> usuarios_1) {
		this.cargo = cargo;
		this.usuarios = usuarios;
		this.usuarios_1 = usuarios_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_cargo", unique = true, nullable = false)
	public Integer getIdCargo() {
		return this.idCargo;
	}

	public void setIdCargo(Integer idCargo) {
		this.idCargo = idCargo;
	}

	@Column(name = "cargo", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	public Set<Usuario> getUsuarios_1() {
		return this.usuarios_1;
	}

	public void setUsuarios_1(Set<Usuario> usuarios_1) {
		this.usuarios_1 = usuarios_1;
	}

}
