package br.edu.ufam.scfpcu.model;
// Generated Jan 9, 2014 11:42:56 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Cidades generated by hbm2java
 */
@Entity
@Table(name = "cidades", catalog = "scfpcu")
public class Cidades implements java.io.Serializable {

	private Integer idCidade;
	private Estados estados;
	private String uf;
	private String nome;
	private Set<Veiculo> veiculosForIdCidadePatual = new HashSet<Veiculo>(0);
	private Set<Veiculo> veiculosForIdCidadePanterior = new HashSet<Veiculo>(0);
	private Set<Veiculo> veiculosForIdCidadePanterior_1 = new HashSet<Veiculo>(
			0);
	private Set<Veiculo> veiculosForIdCidadePatual_1 = new HashSet<Veiculo>(0);

	public Cidades() {
	}

	public Cidades(Estados estados, String uf, String nome) {
		this.estados = estados;
		this.uf = uf;
		this.nome = nome;
	}
	public Cidades(Estados estados, String uf, String nome,
			Set<Veiculo> veiculosForIdCidadePatual,
			Set<Veiculo> veiculosForIdCidadePanterior,
			Set<Veiculo> veiculosForIdCidadePanterior_1,
			Set<Veiculo> veiculosForIdCidadePatual_1) {
		this.estados = estados;
		this.uf = uf;
		this.nome = nome;
		this.veiculosForIdCidadePatual = veiculosForIdCidadePatual;
		this.veiculosForIdCidadePanterior = veiculosForIdCidadePanterior;
		this.veiculosForIdCidadePanterior_1 = veiculosForIdCidadePanterior_1;
		this.veiculosForIdCidadePatual_1 = veiculosForIdCidadePatual_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_cidade", unique = true, nullable = false)
	public Integer getIdCidade() {
		return this.idCidade;
	}

	public void setIdCidade(Integer idCidade) {
		this.idCidade = idCidade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado", nullable = false)
	@NotNull
	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	@Column(name = "uf", nullable = false, length = 4)
	@NotNull
	@Length(max = 4)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@Column(name = "nome", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidadesByIdCidadePatual")
	public Set<Veiculo> getVeiculosForIdCidadePatual() {
		return this.veiculosForIdCidadePatual;
	}

	public void setVeiculosForIdCidadePatual(
			Set<Veiculo> veiculosForIdCidadePatual) {
		this.veiculosForIdCidadePatual = veiculosForIdCidadePatual;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidadesByIdCidadePanterior")
	public Set<Veiculo> getVeiculosForIdCidadePanterior() {
		return this.veiculosForIdCidadePanterior;
	}

	public void setVeiculosForIdCidadePanterior(
			Set<Veiculo> veiculosForIdCidadePanterior) {
		this.veiculosForIdCidadePanterior = veiculosForIdCidadePanterior;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidadesByIdCidadePanterior")
	public Set<Veiculo> getVeiculosForIdCidadePanterior_1() {
		return this.veiculosForIdCidadePanterior_1;
	}

	public void setVeiculosForIdCidadePanterior_1(
			Set<Veiculo> veiculosForIdCidadePanterior_1) {
		this.veiculosForIdCidadePanterior_1 = veiculosForIdCidadePanterior_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidadesByIdCidadePatual")
	public Set<Veiculo> getVeiculosForIdCidadePatual_1() {
		return this.veiculosForIdCidadePatual_1;
	}

	public void setVeiculosForIdCidadePatual_1(
			Set<Veiculo> veiculosForIdCidadePatual_1) {
		this.veiculosForIdCidadePatual_1 = veiculosForIdCidadePatual_1;
	}

}
