package br.edu.ufam.scfpcu.model;
// Generated Jan 9, 2014 11:42:56 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Entidade generated by hbm2java
 */
@Entity
@Table(name = "entidade", catalog = "scfpcu")
public class Entidade implements java.io.Serializable {

	private Integer idEntidade;
	private String tipoEntidade;
	private Set<Veiculo> veiculos = new HashSet<Veiculo>(0);
	private Set<Veiculo> veiculos_1 = new HashSet<Veiculo>(0);

	public Entidade() {
	}

	public Entidade(String tipoEntidade) {
		this.tipoEntidade = tipoEntidade;
	}
	public Entidade(String tipoEntidade, Set<Veiculo> veiculos,
			Set<Veiculo> veiculos_1) {
		this.tipoEntidade = tipoEntidade;
		this.veiculos = veiculos;
		this.veiculos_1 = veiculos_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_entidade", unique = true, nullable = false)
	public Integer getIdEntidade() {
		return this.idEntidade;
	}

	public void setIdEntidade(Integer idEntidade) {
		this.idEntidade = idEntidade;
	}

	@Column(name = "tipo_entidade", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getTipoEntidade() {
		return this.tipoEntidade;
	}

	public void setTipoEntidade(String tipoEntidade) {
		this.tipoEntidade = tipoEntidade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidade")
	public Set<Veiculo> getVeiculos() {
		return this.veiculos;
	}

	public void setVeiculos(Set<Veiculo> veiculos) {
		this.veiculos = veiculos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidade")
	public Set<Veiculo> getVeiculos_1() {
		return this.veiculos_1;
	}

	public void setVeiculos_1(Set<Veiculo> veiculos_1) {
		this.veiculos_1 = veiculos_1;
	}

}
