package br.edu.ufam.scfpcu.model;
// Generated Jan 9, 2014 11:42:56 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Especie generated by hbm2java
 */
@Entity
@Table(name = "especie", catalog = "scfpcu")
public class Especie implements java.io.Serializable {

	private Integer idEspecie;
	private String especie;
	private Set<Veiculo> veiculos = new HashSet<Veiculo>(0);
	private Set<Veiculo> veiculos_1 = new HashSet<Veiculo>(0);

	public Especie() {
	}

	public Especie(String especie) {
		this.especie = especie;
	}
	public Especie(String especie, Set<Veiculo> veiculos,
			Set<Veiculo> veiculos_1) {
		this.especie = especie;
		this.veiculos = veiculos;
		this.veiculos_1 = veiculos_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_especie", unique = true, nullable = false)
	public Integer getIdEspecie() {
		return this.idEspecie;
	}

	public void setIdEspecie(Integer idEspecie) {
		this.idEspecie = idEspecie;
	}

	@Column(name = "especie", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getEspecie() {
		return this.especie;
	}

	public void setEspecie(String especie) {
		this.especie = especie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "especie")
	public Set<Veiculo> getVeiculos() {
		return this.veiculos;
	}

	public void setVeiculos(Set<Veiculo> veiculos) {
		this.veiculos = veiculos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "especie")
	public Set<Veiculo> getVeiculos_1() {
		return this.veiculos_1;
	}

	public void setVeiculos_1(Set<Veiculo> veiculos_1) {
		this.veiculos_1 = veiculos_1;
	}

}
