package br.edu.ufam.scfpcu.model;
// Generated Jan 9, 2014 11:42:56 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name = "estados", catalog = "scfpcu")
public class Estados implements java.io.Serializable {

	private Integer id;
	private String uf;
	private String nome;
	private Set<Cidades> cidadeses = new HashSet<Cidades>(0);
	private Set<Cidades> cidadeses_1 = new HashSet<Cidades>(0);

	public Estados() {
	}

	public Estados(String uf, String nome) {
		this.uf = uf;
		this.nome = nome;
	}
	public Estados(String uf, String nome, Set<Cidades> cidadeses,
			Set<Cidades> cidadeses_1) {
		this.uf = uf;
		this.nome = nome;
		this.cidadeses = cidadeses;
		this.cidadeses_1 = cidadeses_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "uf", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@Column(name = "nome", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estados")
	public Set<Cidades> getCidadeses() {
		return this.cidadeses;
	}

	public void setCidadeses(Set<Cidades> cidadeses) {
		this.cidadeses = cidadeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estados")
	public Set<Cidades> getCidadeses_1() {
		return this.cidadeses_1;
	}

	public void setCidadeses_1(Set<Cidades> cidadeses_1) {
		this.cidadeses_1 = cidadeses_1;
	}

}
