package br.edu.ufam.scfpcu.model;
// Generated Jan 9, 2014 11:42:56 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Gastos generated by hbm2java
 */
@Entity
@Table(name = "gastos", catalog = "scfpcu")
public class Gastos implements java.io.Serializable {

	private Integer idGasto;
	private TipoServico tipoServico;
	private Veiculo veiculo;
	private TipoCombustivel tipoCombustivel;
	private String lotado;
	private Integer odometro;
	private double valor;
	private int qtd;
	private Date data;
	private int tipoGasto;

	public Gastos() {
	}

	public Gastos(Veiculo veiculo, double valor, int qtd, Date data,
			int tipoGasto) {
		this.veiculo = veiculo;
		this.valor = valor;
		this.qtd = qtd;
		this.data = data;
		this.tipoGasto = tipoGasto;
	}
	public Gastos(TipoServico tipoServico, Veiculo veiculo,
			TipoCombustivel tipoCombustivel, String lotado, Integer odometro,
			double valor, int qtd, Date data, int tipoGasto) {
		this.tipoServico = tipoServico;
		this.veiculo = veiculo;
		this.tipoCombustivel = tipoCombustivel;
		this.lotado = lotado;
		this.odometro = odometro;
		this.valor = valor;
		this.qtd = qtd;
		this.data = data;
		this.tipoGasto = tipoGasto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_gasto", unique = true, nullable = false)
	public Integer getIdGasto() {
		return this.idGasto;
	}

	public void setIdGasto(Integer idGasto) {
		this.idGasto = idGasto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_servico")
	public TipoServico getTipoServico() {
		return this.tipoServico;
	}

	public void setTipoServico(TipoServico tipoServico) {
		this.tipoServico = tipoServico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "placa_veiculo", nullable = false)
	@NotNull
	public Veiculo getVeiculo() {
		return this.veiculo;
	}

	public void setVeiculo(Veiculo veiculo) {
		this.veiculo = veiculo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_combustivel")
	public TipoCombustivel getTipoCombustivel() {
		return this.tipoCombustivel;
	}

	public void setTipoCombustivel(TipoCombustivel tipoCombustivel) {
		this.tipoCombustivel = tipoCombustivel;
	}

	@Column(name = "lotado", length = 50)
	@Length(max = 50)
	public String getLotado() {
		return this.lotado;
	}

	public void setLotado(String lotado) {
		this.lotado = lotado;
	}

	@Column(name = "odometro")
	public Integer getOdometro() {
		return this.odometro;
	}

	public void setOdometro(Integer odometro) {
		this.odometro = odometro;
	}

	@Column(name = "valor", nullable = false, precision = 22, scale = 0)
	public double getValor() {
		return this.valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

	@Column(name = "qtd", nullable = false)
	public int getQtd() {
		return this.qtd;
	}

	public void setQtd(int qtd) {
		this.qtd = qtd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", nullable = false, length = 10)
	@NotNull
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "tipo_gasto", nullable = false)
	public int getTipoGasto() {
		return this.tipoGasto;
	}

	public void setTipoGasto(int tipoGasto) {
		this.tipoGasto = tipoGasto;
	}

}
