package br.edu.ufam.scfpcu.model;
// Generated Jan 9, 2014 11:42:56 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name = "grupo", catalog = "scfpcu")
public class Grupo implements java.io.Serializable {

	private Integer idGrupo;
	private String tipoGrupo;
	private Set<Veiculo> veiculos = new HashSet<Veiculo>(0);
	private Set<Veiculo> veiculos_1 = new HashSet<Veiculo>(0);

	public Grupo() {
	}

	public Grupo(String tipoGrupo, Set<Veiculo> veiculos,
			Set<Veiculo> veiculos_1) {
		this.tipoGrupo = tipoGrupo;
		this.veiculos = veiculos;
		this.veiculos_1 = veiculos_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_grupo", unique = true, nullable = false)
	public Integer getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(Integer idGrupo) {
		this.idGrupo = idGrupo;
	}

	@Column(name = "tipo_grupo", length = 10)
	@Length(max = 10)
	public String getTipoGrupo() {
		return this.tipoGrupo;
	}

	public void setTipoGrupo(String tipoGrupo) {
		this.tipoGrupo = tipoGrupo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<Veiculo> getVeiculos() {
		return this.veiculos;
	}

	public void setVeiculos(Set<Veiculo> veiculos) {
		this.veiculos = veiculos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<Veiculo> getVeiculos_1() {
		return this.veiculos_1;
	}

	public void setVeiculos_1(Set<Veiculo> veiculos_1) {
		this.veiculos_1 = veiculos_1;
	}

}
