package br.edu.ufam.scfpcu.model;
// Generated Jan 9, 2014 11:42:56 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "scfpcu")
public class Modelo implements java.io.Serializable {

	private Integer idModelo;
	private Marca marca;
	private String modelo;
	private Set<Veiculo> veiculos = new HashSet<Veiculo>(0);
	private Set<Veiculo> veiculos_1 = new HashSet<Veiculo>(0);

	public Modelo() {
	}

	public Modelo(Marca marca, String modelo) {
		this.marca = marca;
		this.modelo = modelo;
	}
	public Modelo(Marca marca, String modelo, Set<Veiculo> veiculos,
			Set<Veiculo> veiculos_1) {
		this.marca = marca;
		this.modelo = modelo;
		this.veiculos = veiculos;
		this.veiculos_1 = veiculos_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_modelo", unique = true, nullable = false)
	public Integer getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(Integer idModelo) {
		this.idModelo = idModelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_marca", nullable = false)
	@NotNull
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@Column(name = "modelo", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Veiculo> getVeiculos() {
		return this.veiculos;
	}

	public void setVeiculos(Set<Veiculo> veiculos) {
		this.veiculos = veiculos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Veiculo> getVeiculos_1() {
		return this.veiculos_1;
	}

	public void setVeiculos_1(Set<Veiculo> veiculos_1) {
		this.veiculos_1 = veiculos_1;
	}

}
