package br.edu.ufam.scfpcu.model;
// Generated Jan 9, 2014 11:42:56 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Motorista generated by hbm2java
 */
@Entity
@Table(name = "motorista", catalog = "scfpcu")
public class Motorista implements java.io.Serializable {

	private Integer idMotorista;
	private String nome;
	private int cnh;
	private String tipocnh;
	private String rua;
	private String num;
	private String bairro;
	private Integer cep;
	private Integer telefone;
	private int status;

	public Motorista() {
	}

	public Motorista(String nome, int cnh, String tipocnh, int status) {
		this.nome = nome;
		this.cnh = cnh;
		this.tipocnh = tipocnh;
		this.status = status;
	}
	public Motorista(String nome, int cnh, String tipocnh, String rua,
			String num, String bairro, Integer cep, Integer telefone, int status) {
		this.nome = nome;
		this.cnh = cnh;
		this.tipocnh = tipocnh;
		this.rua = rua;
		this.num = num;
		this.bairro = bairro;
		this.cep = cep;
		this.telefone = telefone;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_motorista", unique = true, nullable = false)
	public Integer getIdMotorista() {
		return this.idMotorista;
	}

	public void setIdMotorista(Integer idMotorista) {
		this.idMotorista = idMotorista;
	}

	@Column(name = "Nome", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "Cnh", nullable = false)
	public int getCnh() {
		return this.cnh;
	}

	public void setCnh(int cnh) {
		this.cnh = cnh;
	}

	@Column(name = "Tipocnh", nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getTipocnh() {
		return this.tipocnh;
	}

	public void setTipocnh(String tipocnh) {
		this.tipocnh = tipocnh;
	}

	@Column(name = "Rua", length = 100)
	@Length(max = 100)
	public String getRua() {
		return this.rua;
	}

	public void setRua(String rua) {
		this.rua = rua;
	}

	@Column(name = "Num", length = 10)
	@Length(max = 10)
	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	@Column(name = "Bairro", length = 50)
	@Length(max = 50)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "Cep")
	public Integer getCep() {
		return this.cep;
	}

	public void setCep(Integer cep) {
		this.cep = cep;
	}

	@Column(name = "Telefone")
	public Integer getTelefone() {
		return this.telefone;
	}

	public void setTelefone(Integer telefone) {
		this.telefone = telefone;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
