package br.edu.ufam.scfpcu.model;
// Generated Jan 9, 2014 11:42:56 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoServico generated by hbm2java
 */
@Entity
@Table(name = "tipo_servico", catalog = "scfpcu")
public class TipoServico implements java.io.Serializable {

	private Integer idServico;
	private String servico;
	private Set<Gastos> gastoses = new HashSet<Gastos>(0);
	private Set<Gastos> gastoses_1 = new HashSet<Gastos>(0);

	public TipoServico() {
	}

	public TipoServico(String servico) {
		this.servico = servico;
	}
	public TipoServico(String servico, Set<Gastos> gastoses,
			Set<Gastos> gastoses_1) {
		this.servico = servico;
		this.gastoses = gastoses;
		this.gastoses_1 = gastoses_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_servico", unique = true, nullable = false)
	public Integer getIdServico() {
		return this.idServico;
	}

	public void setIdServico(Integer idServico) {
		this.idServico = idServico;
	}

	@Column(name = "servico", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getServico() {
		return this.servico;
	}

	public void setServico(String servico) {
		this.servico = servico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoServico")
	public Set<Gastos> getGastoses() {
		return this.gastoses;
	}

	public void setGastoses(Set<Gastos> gastoses) {
		this.gastoses = gastoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoServico")
	public Set<Gastos> getGastoses_1() {
		return this.gastoses_1;
	}

	public void setGastoses_1(Set<Gastos> gastoses_1) {
		this.gastoses_1 = gastoses_1;
	}

}
