package br.edu.ufam.scfpcu.model;
// Generated Jan 9, 2014 11:42:56 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "scfpcu")
public class Usuario implements java.io.Serializable {

	private int idServidor;
	private Cargo cargo;
	private String siape;
	private String nome;
	private String email;
	private int login;
	private int senha;

	public Usuario() {
	}

	public Usuario(int idServidor, Cargo cargo, String siape, String nome,
			String email, int login, int senha) {
		this.idServidor = idServidor;
		this.cargo = cargo;
		this.siape = siape;
		this.nome = nome;
		this.email = email;
		this.login = login;
		this.senha = senha;
	}

	@Id
	@Column(name = "id_servidor", unique = true, nullable = false)
	public int getIdServidor() {
		return this.idServidor;
	}

	public void setIdServidor(int idServidor) {
		this.idServidor = idServidor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cargo", nullable = false)
	@NotNull
	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	@Column(name = "SIAPE", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getSiape() {
		return this.siape;
	}

	public void setSiape(String siape) {
		this.siape = siape;
	}

	@Column(name = "Nome", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "Email", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Login", nullable = false)
	public int getLogin() {
		return this.login;
	}

	public void setLogin(int login) {
		this.login = login;
	}

	@Column(name = "Senha", nullable = false)
	public int getSenha() {
		return this.senha;
	}

	public void setSenha(int senha) {
		this.senha = senha;
	}

}
